### ISSUE TITLE
Compiling fails - Cannot find "yay/alice-vision-git/src/build/src/doc"

### ISSUE THREAD

**Issue by ngreve** [bartoszek/AUR-alice-vision-git#2]
[Unfortunately I also reported this issue to the official repo.](https://github.com/alicevision/AliceVision/issues/692). Should I ask them to close it?

### Problem
does not compile

**Expected behavior:**
it should compile

**Actual behavior:**
```
CMake Error at src/cmake_install.cmake:45 (file):
  file INSTALL cannot find
  "/home/nico/.cache/yay/alice-vision-git/src/build/src/doc".
Call Stack (most recent call first):
  cmake_install.cmake:51 (include)


make: *** [Makefile:118: install] Error 1
==> ERROR: A failure occurred in package().
    Aborting...
Error making: alice-vision-git

```

### Steps to Reproduce

yay -S alice-vision-git

actually just trying to upgrade (2.1.0.r71.g5c5a65a3-1 -> 2.2.0.r17.g63a3d6ad-1), but because the error happens when compiling, I do not assume it has something to do with the upgrading process

### Versions

* AliceVision branch/version: [AUR](https://aur.archlinux.org/packages/alice-vision-git/)
* OS: Arch Linux 5.2.14-arch2-1
* C++ compiler: gcc version 9.1.0 (GCC)

**Comment by bartoszek** [comment]
Yep, this is AUR specific issue. Or more specifically `yay` issue :smirk: I'll work this out at evening.

**Comment by bartoszek** [comment]
@ngreve This issue looks really strange, can't even find `INSTALL` file in `alice-vision` sources (despite dependencies). I've run this is Clean Env without any problem (`cmake_install.cmake` doesn't contains anny references to `/doc/` or `INSTALL` :confused: )

Can you run `makepkg -Csr` in `~/.cache/yay/alice-vision-git` and report if it works when excluding yay quirks :thinking:

```sh
cd ~/.cache/yay/alice-vision-git && makepkg -Csr
```

**Comment by ngreve** [comment]
Nope, does not work either :/. Same error, I just appended more of the console output: 

```
. . .

-- Installing: /home/nico/.cache/yay/alice-vision-git/pkg/alice-vision-git/usr/include/aliceVision_dependencies/osi_clp/CoinUtils/src/CoinModelUseful.hpp
-- Installing: /home/nico/.cache/yay/alice-vision-git/pkg/alice-vision-git/usr/include/aliceVision_dependencies/osi_clp/CoinUtils/src/CoinPresolveZeros.hpp
-- Installing: /home/nico/.cache/yay/alice-vision-git/pkg/alice-vision-git/usr/include/aliceVision_dependencies/osi_clp/CoinUtils/src/CoinPresolveSubst.hpp
-- Installing: /home/nico/.cache/yay/alice-vision-git/pkg/alice-vision-git/usr/include/aliceVision_dependencies/osi_clp/CoinUtils/src/CoinModel.hpp
-- Installing: /home/nico/.cache/yay/alice-vision-git/pkg/alice-vision-git/usr/include/aliceVision_dependencies/osi_clp/CoinUtils/src/CoinPresolveTighten.hpp
-- Installing: /home/nico/.cache/yay/alice-vision-git/pkg/alice-vision-git/usr/include/aliceVision_dependencies/osi_clp/CoinUtils/src/CoinPresolveDual.hpp
-- Installing: /home/nico/.cache/yay/alice-vision-git/pkg/alice-vision-git/usr/include/aliceVision_dependencies/osi_clp/CoinUtils/src/CoinFileIO.hpp
-- Installing: /home/nico/.cache/yay/alice-vision-git/pkg/alice-vision-git/usr/include/aliceVision_dependencies/cxsparse
-- Installing: /home/nico/.cache/yay/alice-vision-git/pkg/alice-vision-git/usr/include/aliceVision_dependencies/cxsparse/Include
-- Installing: /home/nico/.cache/yay/alice-vision-git/pkg/alice-vision-git/usr/include/aliceVision_dependencies/cxsparse/Include/cs.h
-- Installing: /home/nico/.cache/yay/alice-vision-git/pkg/alice-vision-git/usr/include/aliceVision_dependencies/cxsparse/Include/SuiteSparse_config.h
-- Installing: /home/nico/.cache/yay/alice-vision-git/pkg/alice-vision-git/usr/include/aliceVision_dependencies/cxsparse/Source
-- Installing: /home/nico/.cache/yay/alice-vision-git/pkg/alice-vision-git/usr/include/aliceVision_dependencies/cxsparse/Doc
CMake Error at src/cmake_install.cmake:45 (file):
  file INSTALL cannot find
  "/home/nico/.cache/yay/alice-vision-git/src/build/src/doc".
Call Stack (most recent call first):
  cmake_install.cmake:51 (include)


make: *** [Makefile:118: install] Error 1
==> ERROR: A failure occurred in package().
    Aborting...
```

**Comment by bartoszek** [comment]
@ngreve could you please pack `.cache/yay/alice-vision-git/src/build` (it should be there after running `makepkg`) and put it in comment (drag & drop file on to GitHub comment box).
```sh
tar cJf alice-vision-build.tar.gz ~/.cache/yay/alice-vision-git/src/build
```

**Comment by ngreve** [comment]
[alice-vision-build.tar.gz](https://github.com/bartoszek/AUR-alice-vision-git/files/3612940/alice-vision-build.tar.gz)
thanks for the great support so far!

Maybe the yay version matters: yay v9.2.1 - libalpm v11.0.3

**Comment by bartoszek** [comment]
@ngreve Fixed with https://github.com/bartoszek/AUR-alice-vision-git/commit/35a5549a6dd0024e4b41d6b786014d66210bfd8b
